<a href="https://colab.research.google.com/github/cupofphotones/pytorch/blob/master/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

In [4]:
x = torch.rand(5,3)
print(x)

y = x
print(y)

tensor([[0.1016, 0.5445, 0.8837],
        [0.0227, 0.9891, 0.7365],
        [0.2921, 0.0845, 0.0626],
        [0.2022, 0.5263, 0.2230],
        [0.7080, 0.6925, 0.0185]])
tensor([[0.1016, 0.5445, 0.8837],
        [0.0227, 0.9891, 0.7365],
        [0.2921, 0.0845, 0.0626],
        [0.2022, 0.5263, 0.2230],
        [0.7080, 0.6925, 0.0185]])


In [6]:
print(x+y)

tensor([[0.2033, 1.0890, 1.7674],
        [0.0454, 1.9782, 1.4729],
        [0.5841, 0.1689, 0.1253],
        [0.4044, 1.0525, 0.4461],
        [1.4160, 1.3850, 0.0371]])


In [0]:
print(torch.add(x,y))

tensor([[0.7680, 0.4829, 1.3779],
        [0.7299, 1.6297, 1.6304],
        [1.4368, 1.3785, 1.4343],
        [0.1407, 0.2274, 1.8740],
        [0.2686, 1.6724, 0.0404]])


In [5]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[0.2033, 1.0890, 1.7674],
        [0.0454, 1.9782, 1.4729],
        [0.5841, 0.1689, 0.1253],
        [0.4044, 1.0525, 0.4461],
        [1.4160, 1.3850, 0.0371]])


In [7]:
y.add_(x)
print(y)

tensor([[0.2033, 1.0890, 1.7674],
        [0.0454, 1.9782, 1.4729],
        [0.5841, 0.1689, 0.1253],
        [0.4044, 1.0525, 0.4461],
        [1.4160, 1.3850, 0.0371]])


In [9]:
print(y[:,1])

tensor([1.0890, 1.9782, 0.1689, 1.0525, 1.3850])


In [10]:
print(y[1,1])

tensor(1.9782)


In [11]:
print(y[:,0])

tensor([0.2033, 0.0454, 0.5841, 0.4044, 1.4160])


In [12]:
print(y[0,:])

tensor([0.2033, 1.0890, 1.7674])


In [23]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,2)
print(x)
print('______________________________')
print(y)
print('______________________________')
print(z)

tensor([[-0.2189, -0.2576, -0.1038, -1.4113],
        [ 1.5965, -0.3566, -0.3301,  1.2188],
        [-0.3548,  0.2809, -0.6365, -0.5077],
        [-0.7210,  1.3403, -0.5838,  0.4997]])
______________________________
tensor([-0.2189, -0.2576, -0.1038, -1.4113,  1.5965, -0.3566, -0.3301,  1.2188,
        -0.3548,  0.2809, -0.6365, -0.5077, -0.7210,  1.3403, -0.5838,  0.4997])
______________________________
tensor([[-0.2189, -0.2576],
        [-0.1038, -1.4113],
        [ 1.5965, -0.3566],
        [-0.3301,  1.2188],
        [-0.3548,  0.2809],
        [-0.6365, -0.5077],
        [-0.7210,  1.3403],
        [-0.5838,  0.4997]])


In [24]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.6623])
0.662338018417


In [0]:
x = torch.rand(5,5)

In [30]:
print(x[2,2])

tensor(0.8294)


In [31]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [32]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [33]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [35]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [37]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = x+y
  print(z)
  print(z.to("cpu",torch.double))

tensor([[1.0817, 1.3105, 1.6061, 1.3522, 1.6026],
        [1.7678, 1.4497, 1.8707, 1.8203, 1.0456],
        [1.3056, 1.0148, 1.8294, 1.8881, 1.1563],
        [1.4729, 1.3273, 1.5772, 1.9568, 1.4172],
        [1.5642, 1.1046, 1.4708, 1.3402, 1.0347]], device='cuda:0')
tensor([[1.0817, 1.3105, 1.6061, 1.3522, 1.6026],
        [1.7678, 1.4497, 1.8707, 1.8203, 1.0456],
        [1.3056, 1.0148, 1.8294, 1.8881, 1.1563],
        [1.4729, 1.3273, 1.5772, 1.9568, 1.4172],
        [1.5642, 1.1046, 1.4708, 1.3402, 1.0347]], dtype=torch.float64)


In [38]:
x3 = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]])
print('------------------------------')
print(x3[0,0,0])
print('------------------------------')
print(x3[:,0,0])
print('------------------------------')
print(x3[0,:,0])
print('------------------------------')
print(x3[0,0,:])
print('------------------------------')

------------------------------
tensor(1)
------------------------------
tensor([1])
------------------------------
tensor([ 1,  5,  9, 13])
------------------------------
tensor([1, 2, 3, 4])
------------------------------


In [39]:
print([8,0,0])

[8, 0, 0]


In [47]:
print(x3[0,1,0])

tensor(5)


In [49]:
print(x3[0,0,1])

tensor(2)


In [54]:
print(x3[0,2,0])

tensor(9)
